### ISSUE TITLE
Any user's email is basically public

### ISSUE THREAD

**Issue by matt-kempster** [manifoldmarkets/manifold#1119]
After network-sniffing a bit, I quickly realized that when going to a user's profile, that user's email address is returned in the JSON info blob. 

This info should not be public. Can we drop it server-side before sending it to the client?

**Comment by matt-kempster** [comment]
Actually it appears this only affects some users. The exact location of the emails I did see were at `["pageProps"]["user"]["email"]`.

(I haven't taken a look at the source code whatsoever so I'm sure it's more obvious to those who have.)

**Comment by jahooma** [comment]
Thank you, Matt, for bringing this to our attention!

We normally store email addresses in a special collection with permissions that prevent other users from accessing them. However, user emails were recently copied into our public collection of users mistakenly.

I've just written and executed a script to remove user's email address from our public collection. It should no longer be possible to access users' email addresses.

We'll work on a process within our team to ensure this doesn't happen again.

Also, since you brought this to our attention, we want to award you a bounty (in M$). Please let me know your Manifold  username, and I'll get that to you! (Plus we'll add you to our cool [bounties page](https://docs.manifold.markets/bounties).)

P.S. In the future, for a sensitive issue, it's better to email us or DM one of use on Discord, so the exploit is not advertised for others to take advantage of, haha.

**Comment by matt-kempster** [comment]
I've emailed info@manifold.markets for more info.

**Comment by jahooma** [comment]
Thanks Matt! Got the email.
