### ISSUE TITLE
Can't change my username

### ISSUE THREAD

**Issue by jahooma** [manifoldmarkets/manifold#196]
When I try to change my user name in /profile, it changes back shortly after unfocusing the input.

![Screen Shot 2022-05-12 at 11 35 21 AM](https://user-images.githubusercontent.com/1593821/168113656-2af9afa9-d66d-4595-b22d-6378d07280e9.png)

**Comment by mcapodici** [comment]
I might take a look at this bug out of curiosity, and the challenge. I can reproduce it with my username, so it is not a special admin-related thing. Just want to check if you still want someone to look at it?

**Comment by jahooma** [comment]
Sure! Seems like something we should fix. Thanks.

**Comment by mcapodici** [comment]
Initial findings:

I had a quick look, and this is reproducible on prod but not dev.

On prod, when changing the name the error is shown in the console against the network:

```
Object { status: "error", message: "3 INVALID_ARGUMENT: maximum 500 writes allowed per request" }
```

In the code, when any error occurs, this line swallows the error and reverts the username: https://github.com/manifoldmarkets/manifold/blob/6cc2d8af58bf9680ba2574e2fec4e93c25882518/web/pages/profile.tsx#L107

**Comment by mcapodici** [comment]
I have a suspicion that `renameUserContracts` might be the reason, or some similar function. Because the request from the browser is a simple one: {"data":{"username":"new name"}}, so it can't be the reason for the > 500 requests in a batch issue.

**Comment by mcapodici** [comment]
I think the reason for this is that a function tries to update all the places (contracts, comments, not bets though??) where your username existed. This is the reference:

https://github.com/manifoldmarkets/manifold/blob/1075fec53fe68855fd9d57b9cfceb0a3369a5416/functions/src/change-user-info.ts#L15

There are some solutions I can think of, but need input to help:

- Catch the specific error. Notify user that they cannot change their name. 
- A periodic job to do the updating of all the things that need updating. Eventual consistency.
- Don't do all that updating at all. Historic use of your username is not changed.
- Restructure database so that you don't store the name on leafs everywhere. I think this would mean exposing the userid-username mapping to the client. Maybe you don't want to expose that for privacy/security reasons? Or just for performance.

**Comment by mcapodici** [comment]
Will leave it there for now. If I get time tomorrow I might try to reproduce on the local emulator to confirm my hypothesis in the last comment.

**Comment by mcapodici** [comment]
Hmm. Bit of a stumbling block running the local emulator, has anyone else encountered this? 

```
user:~/manifold/functions$ yarn serve
yarn run v1.22.18
$ yarn build && firebase emulators:start --only functions,firestore --import=./firestore_export
$ tsc
i  emulators: Starting emulators: functions, firestore
i  emulators: Shutting down emulators.

Error: An unexpected error has occurred.

Having trouble? Try again or contact support with contents of firebase-debug.log
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
user~/manifold/functions$ 
```
