### ISSUE TITLE
[FR] Allow the creator of a "Free response" market to restrict the creation of new answers

### ISSUE THREAD

**Issue by omarkohl** [manifoldmarkets/manifold#983]
This seems like a quick fix that works around some of the current difficulties with "free response" markets. For example duplicate or overlapping answers will be avoided.

Add a check box "Only creator can add answers".

**Comment by sipec** [comment]
We used to have a multiple choice feature that worked exactly like this, but we removed it because the market mechanism behind free response markets (dynamic parimutuel) is not a good experience to trade on.

Hopefully this quarter we'll give some love to the free response / multi choice market mechanism

**Comment by omarkohl** [comment]
I was able to create one such "multi choice" market just now, so I assume this has been implemented :partying_face:

**Comment by sipec** [comment]
Indeed steven just re-added the feature!

**Comment by sipec** [comment]
It costs a bit more than the YES/NO questions. We do want to discourage it for the time being while we work on a better mechanism for the multi choice market. But you can do it!
